module.exports = [
{name : "Ariana"},
{name : "Béja"},
{name : "Ben Arous"},
{name : "Bizerte"},
{name : "Gabès"},
{name : "Gafsa"},
{name : "Jendouba"},
{name : "Kairouan"},
{name : "Kasserine"},
{name : "Kébili"},
{name : "La Manouba"},
{name : "Le Kef"},
{name : "Mahdia"},
{name : "Médenine"},
{name : "Monastir"},
{name : "Nabeul"},
{name : "Sfax"},
{name : "Sidi Bouzid"},
{name : "Siliana"},
{name : "Sousse"},
{name : "Tataouine"},
{name : "Tozeur"},
{name : "Tunis"},
{name : "Zaghouan"}]